### ISSUE TITLE
Custom CSS `@function` Functions & Mixins

### ISSUE THREAD

**Issue by czerkies** [czerkies/romanczerkies.31#164]
- https://github.com/w3c/csswg-drafts/issues/9350
- https://drafts.csswg.org/css-mixins/

```css
/* custom functions */
@function <name> [(<parameter-list>)]? {
  <function-logic-and-output>
}

/* custom mixins */
@mixin <name> [(<parameter-list>)]? {
  <mixin-logic-and-output>
}
```

new example:
```css
@function --example(--named-parameter <type>: default-value) returns <type> {
    result: var(--named-parameter);
}
```

deprecated:
```css
@function --example(--named-parameter; --name-with: default-value) { 
  /* if further description of a parameter is necessary */
  @parameter --named-parameter {
    default: 2em;
    syntax: "<length>";
  }
}
```
